### ISSUE TITLE
Projectile throw feature

### ISSUE THREAD

**Issue by Labae** [TeamSTEP/catch.io-project-board#25]
**Describe the bug**
The projectile throw feature is not rendering on other clients. However, it seems to work on the host+client side.

**To Reproduce**
1. Build the file.
2. Start a client+host session on the engine
3. Open the built client program and join the opened session
4. Throw an object from either of the builds. You can see that it does not work on the client application

**Expected behavior**
Any thrown objects should render exactly the same as the host

**Screenshots**
### HOST 
![Host](https://user-images.githubusercontent.com/46157657/90210359-b41bcb80-de28-11ea-92ed-4f0a81a9b84b.PNG)

### HOST_HIERARCHY
![SPAWN PROJECTILE](https://user-images.githubusercontent.com/46157657/90210381-c39b1480-de28-11ea-8df3-457190b9d78e.PNG)

### CLIENT
![client](https://user-images.githubusercontent.com/46157657/90210363-b67e2580-de28-11ea-9662-12ce32f3db96.PNG)

**Additional context**
In my opinion, `ExecuteObjectProjectileMotion.ThrowObject` is not behaving the way we expect it should.
![not working on client](https://user-images.githubusercontent.com/46157657/90210407-d31a5d80-de28-11ea-9154-cb448012b859.PNG)

It's my first time using the network. so I think this code is weird.
If we use the `ClientRpc` attribute, we will be able to solve the problem. but I don't know how to use `ClientRpc` to solve this problem.

**Comment by hoonsubin** [comment]
this can be worked after we migrate to Photon 2 https://github.com/TeamSTEP/Catch.ioProjectBoard/issues/27
